// central place for route names to avoid typos.
// `as const` — qiymatlar literal tip bo'lib qoladi (navigation param-list tiplari uchun zarur).
export const ROUTES = {
  DEBTS: 'HisobKitob',
  GAP: 'GapKassa',
  GAP_LIST: 'GapList',
  GAP_DETAIL: 'GapDetail',
  GAP_MEMBER: 'GapMember',
  EXPENSES: 'Expenses',
  PROFILE: 'Profile',
  PROFILE_HOME: 'ProfileHome',
  PROFILE_EDIT: 'ProfileEdit',
  PROFILE_SETTINGS: 'ProfileSettings',
  DEBT_LIST: 'DebtList',
  CONTACT_DETAIL: 'ContactDetail',
  NOTIFICATIONS: 'Notifications',
  EXPENSE_CATEGORIES: 'ExpenseCategories',
  EXPENSE_CATEGORY_DETAIL: 'ExpenseCategoryDetail',
  MY_BUSINESSES: 'MyBusinesses',
  BUSINESS_MEMBERS: 'BusinessMembers',
  OFFER: 'Offer',
  TERMS: 'Terms',
  PRIVACY_POLICY: 'PrivacyPolicy',
  ABOUT_APP: 'AboutApp',
} as const;
